version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: cred-ability-postgres
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: credability_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cred-ability-network

  redis:
    image: redis:7-alpine
    container_name: cred-ability-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cred-ability-network

  adminer:
    image: adminer
    container_name: cred-ability-adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cred-ability-network
    depends_on:
      - postgres

networks:
  cred-ability-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
